import { query, withTransaction } from '../db/database.js';
import { AppError } from '../utils/http.js';
import { id, now } from '../utils/id.js';
import { findWorkerById } from './users.js';
import { notify, notifyRole } from './notifications.js';
export const CATEGORIES=[{id:'road',label:'Road Damage'},{id:'light',label:'Street Light'},{id:'garbage',label:'Garbage'},{id:'water',label:'Water'},{id:'other',label:'Other'}];
export const STATUSES=['submitted','review','assigned','progress','resolved','rejected']; export const PRIORITIES=['Low','Medium','High'];
const categoryDepartment={road:'Roads & Infrastructure',light:'Electrical',garbage:'Sanitation',water:'Water Works',other:'Municipal Services'};
const rowBase=`SELECT c.*,u.name citizen_name,u.email citizen_email,u.mobile citizen_mobile,w.name worker_name,w.worker_id worker_code,w.phone worker_phone,w.department worker_department,a.name authority_name FROM complaints c JOIN users u ON u.id=c.citizen_id LEFT JOIN users w ON w.id=c.worker_id LEFT JOIN users a ON a.id=c.assigned_by`;
async function mapComplaint(c){const {rows:photos}=await query('SELECT id,type,url,caption,created_at AS "createdAt" FROM complaint_photos WHERE complaint_id=$1 ORDER BY created_at ASC',[c.id]);return {id:c.id,citizenId:c.citizen_id,category:c.category,description:c.description,location:c.location,coords:c.lat==null||c.lng==null?null:{lat:c.lat,lng:c.lng},photo:c.photo_url,status:c.status,priority:c.priority,createdAt:c.created_at,updatedAt:c.updated_at,assignedOn:c.assigned_at,expectedBy:c.expected_by,completedOn:c.completed_at,note:c.note,citizen:c.citizen_name?{name:c.citizen_name,email:c.citizen_email,mobile:c.citizen_mobile}:null,worker:c.worker_id?{id:c.worker_id,workerId:c.worker_code,name:c.worker_name,phone:c.worker_phone,department:c.worker_department}:null,assignedBy:c.authority_name||null,workPhotos:{progress:photos.filter(p=>p.type==='progress'),completion:photos.find(p=>p.type==='completion')||null}};}
export async function getComplaint(idValue){const {rows}=await query(`${rowBase} WHERE c.id=$1`,[idValue]);return rows[0]?mapComplaint(rows[0]):null;}
export async function requireComplaint(idValue){const c=await getComplaint(idValue);if(!c)throw new AppError(404,'Complaint not found.');return c;}
export async function listCitizenComplaints(citizenId,{status,category,q}={}){const {rows}=await query(`${rowBase} WHERE c.citizen_id=$1 ORDER BY c.created_at DESC`,[citizenId]);const mapped=await Promise.all(rows.map(mapComplaint));return mapped.filter(c=>(!status||c.status===status)&&(!category||c.category===category)&&(!q||`${c.id} ${c.description} ${c.location}`.toLowerCase().includes(q.toLowerCase())));}
export async function listAuthorityComplaints({status,priority,category,q}={}){const {rows}=await query(`${rowBase} ORDER BY c.created_at DESC`);const mapped=await Promise.all(rows.map(mapComplaint));return mapped.filter(c=>(!status||c.status===status)&&(!priority||c.priority===priority)&&(!category||c.category===category)&&(!q||`${c.id} ${c.description} ${c.location} ${c.citizen?.name||''}`.toLowerCase().includes(q.toLowerCase())));}
export async function listWorkerTasks(workerUserId,{status}={}){const {rows}=await query(`${rowBase} WHERE c.worker_id=$1 ORDER BY CASE c.status WHEN 'progress' THEN 1 WHEN 'assigned' THEN 2 WHEN 'resolved' THEN 3 ELSE 4 END,c.created_at DESC`,[workerUserId]);const mapped=await Promise.all(rows.map(mapComplaint));return mapped.filter(c=>!status||c.status===status);}
export async function createComplaint(citizenId,input,photoUrl=null){const complaintId=`CC-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,timestamp=now();await withTransaction(async client=>{await client.query('INSERT INTO complaints (id,citizen_id,category,description,location,lat,lng,photo_url,status,priority,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11)',[complaintId,citizenId,input.category,input.description,input.location,input.lat??null,input.lng??null,photoUrl,'submitted','Medium',timestamp]);await client.query('INSERT INTO notifications (id,user_id,complaint_id,title,body,created_at) VALUES ($1,$2,$3,$4,$5,$6)',[id('ntf_'),citizenId,complaintId,'Complaint submitted',`Your complaint ${complaintId} has been logged successfully.`,timestamp]);});await notifyRole('authority',{complaintId,title:'New complaint received',body:`${complaintId} (${input.category}) was reported at ${input.location}.`});return getComplaint(complaintId);}
export async function rankWorkers(complaintIdValue){const c=await requireComplaint(complaintIdValue);const {rows:workers}=await query("SELECT * FROM users WHERE role='worker' AND active=TRUE ORDER BY name");const {rows:counts}=await query("SELECT worker_id,COUNT(*)::int AS count FROM complaints WHERE worker_id IS NOT NULL AND status NOT IN ('resolved','rejected') GROUP BY worker_id");const countMap=Object.fromEntries(counts.map(r=>[r.worker_id,r.count]));const dept=categoryDepartment[c.category];return workers.map(w=>({id:w.id,workerId:w.worker_id,name:w.name,department:w.department,ward:w.area,phone:w.phone,activeTasks:countMap[w.id]||0,departmentMatch:w.department===dept||w.department==='Municipal Services',distance:null})).filter(w=>w.departmentMatch).sort((a,b)=>a.activeTasks-b.activeTasks||a.name.localeCompare(b.name));}
export async function assignWorker(authorityId,complaintIdValue,{workerId,priority='Medium',note=''}){const complaint=await requireComplaint(complaintIdValue);if(!['submitted','review','assigned'].includes(complaint.status))throw new AppError(409,'Only open complaints can be assigned or reassigned.');const worker=await findWorkerById(workerId);if(!worker)throw new AppError(404,'Worker not found.');const leadDays={High:2,Medium:4,Low:6}[priority]||4,assignedAt=new Date(),expected=new Date(assignedAt);expected.setDate(expected.getDate()+leadDays);await withTransaction(async client=>{await client.query(`UPDATE complaints SET worker_id=$1,assigned_by=$2,assigned_at=$3,expected_by=$4,priority=$5,note=$6,status='assigned',updated_at=$7 WHERE id=$8`,[worker.id,authorityId,assignedAt,expected,priority,note||null,now(),complaintIdValue]);await client.query('INSERT INTO notifications (id,user_id,complaint_id,title,body,created_at) VALUES ($1,$2,$3,$4,$5,$6),($7,$8,$3,$9,$10,$6)',[id('ntf_'),complaint.citizenId,complaintIdValue,'A worker has been assigned',`${complaintIdValue} has been assigned to ${worker.name}.`,now(),id('ntf_'),worker.id,'New task assigned',`You have been assigned ${complaintIdValue}: ${complaint.description}`]);});return getComplaint(complaintIdValue);}
export async function startTask(workerId,complaintIdValue){const c=await requireComplaint(complaintIdValue);if(c.worker?.id!==workerId)throw new AppError(403,'This task is not assigned to you.');if(c.status==='progress')return c;if(c.status!=='assigned')throw new AppError(409,'Task cannot be started from its current status.');await query("UPDATE complaints SET status='progress',updated_at=$1 WHERE id=$2",[now(),complaintIdValue]);await notify({userId:c.citizenId,complaintId:complaintIdValue,title:'Work has started on your complaint',body:`A worker is now working on ${complaintIdValue}.`});await notifyRole('authority',{complaintId:complaintIdValue,title:'Work started',body:`${c.worker?.name||'A worker'} started ${complaintIdValue}.`});return getComplaint(complaintIdValue);}
export async function addPhoto(workerId,complaintIdValue,type,file,caption=''){const c=await requireComplaint(complaintIdValue);if(c.worker?.id!==workerId)throw new AppError(403,'This task is not assigned to you.');if(c.status!=='progress')throw new AppError(409,'Start the task before uploading work photos.');if(type==='progress'){const {rows}=await query("SELECT COUNT(*)::int AS count FROM complaint_photos WHERE complaint_id=$1 AND type='progress'",[complaintIdValue]);if(rows[0].count>=4)throw new AppError(409,'A maximum of 4 progress photos is allowed.');}if(type==='completion')await query("DELETE FROM complaint_photos WHERE complaint_id=$1 AND type='completion'",[complaintIdValue]);await query('INSERT INTO complaint_photos (id,complaint_id,worker_id,type,url,caption,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7)',[id('photo_'),complaintIdValue,workerId,type,file.url,caption||null,now()]);await query('UPDATE complaints SET updated_at=$1 WHERE id=$2',[now(),complaintIdValue]);return getComplaint(complaintIdValue);}
export async function removePhoto(workerId,complaintIdValue,photoId){const c=await requireComplaint(complaintIdValue);if(c.worker?.id!==workerId)throw new AppError(403,'This task is not assigned to you.');const r=await query("DELETE FROM complaint_photos WHERE id=$1 AND complaint_id=$2 AND worker_id=$3 AND type='progress'",[photoId,complaintIdValue,workerId]);if(!r.rowCount)throw new AppError(404,'Progress photo not found.');return getComplaint(complaintIdValue);}
export async function completeTask(workerId,complaintIdValue){const c=await requireComplaint(complaintIdValue);if(c.worker?.id!==workerId)throw new AppError(403,'This task is not assigned to you.');if(c.status!=='progress')throw new AppError(409,'Task must be in progress before completion.');const {rows}=await query("SELECT id FROM complaint_photos WHERE complaint_id=$1 AND type='completion' LIMIT 1",[complaintIdValue]);if(!rows[0])throw new AppError(409,'A completion photo is required before closing the task.');const timestamp=now();await query("UPDATE complaints SET status='resolved',completed_at=$1,updated_at=$1 WHERE id=$2",[timestamp,complaintIdValue]);await notify({userId:c.citizenId,complaintId:complaintIdValue,title:'Your reported issue has been resolved',body:`${complaintIdValue} has been completed by ${c.worker?.name||'the field worker'}.`});await notifyRole('authority',{complaintId:complaintIdValue,title:'Task completed',body:`${complaintIdValue} was completed by ${c.worker?.name||'the field worker'}.`});return getComplaint(complaintIdValue);}
export async function dashboardForCitizen(citizenId){const rows=await listCitizenComplaints(citizenId);return{total:rows.length,active:rows.filter(c=>!['resolved','rejected'].includes(c.status)).length,resolved:rows.filter(c=>c.status==='resolved').length,inProgress:rows.filter(c=>c.status==='progress').length,recent:rows.slice(0,3)};}
export async function dashboardForAuthority(){const rows=await listAuthorityComplaints();return{total:rows.length,new:rows.filter(c=>c.status==='submitted'||c.status==='review').length,pending:rows.filter(c=>c.status==='assigned').length,inProgress:rows.filter(c=>c.status==='progress').length,completed:rows.filter(c=>c.status==='resolved').length,recent:rows.slice(0,6)};}
