import { query } from '../db/database.js';
import { id, now } from '../utils/id.js';
import { hashPassword, verifyPassword } from '../utils/auth.js';
import { AppError } from '../utils/http.js';
const publicUser = u => u && ({ id:u.id,role:u.role,name:u.name,email:u.email,mobile:u.mobile,username:u.username,employeeId:u.employee_id,phone:u.phone,area:u.area,workerId:u.worker_id,department:u.department });
export async function findUserById(userId){ const {rows}=await query('SELECT * FROM users WHERE id=$1',[userId]); return rows[0]||null; }
export async function publicUserById(userId){ return publicUser(await findUserById(userId)); }
export async function findWorkerById(workerId){ const {rows}=await query("SELECT * FROM users WHERE role='worker' AND worker_id=$1 AND active=TRUE",[workerId]); return rows[0]||null; }
export async function listWorkers(){ const {rows}=await query("SELECT * FROM users WHERE role='worker' AND active=TRUE ORDER BY name"); return rows.map(publicUser); }
const nullish=v=>v===undefined||v===''?null:v;
export async function registerUser({role,name,email,mobile,username,employeeId,password,phone,area}){ const idValue=id('usr_'), timestamp=now(), workerId=role==='worker'?`CW-${Math.floor(1000+Math.random()*9000)}`:null, department=role==='worker'?'Municipal Services':null, hash=await hashPassword(password); try { await query(`INSERT INTO users (id,role,name,email,mobile,username,employee_id,password_hash,phone,area,worker_id,department,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13)`,[idValue,role,name,nullish(email),nullish(mobile),nullish(username),nullish(employeeId),hash,nullish(phone),nullish(area),workerId,department,timestamp]); } catch(e){ if(e.code==='23505') throw new AppError(409,'An account with those details already exists.'); throw e; } return findUserById(idValue); }
export async function authenticate(identifier,password){ const normalized=identifier.trim().toLowerCase(); const digits=/[a-z@]/i.test(identifier)?'':identifier.replace(/\D/g,'').slice(-10); const {rows}=await query("SELECT * FROM users WHERE lower(coalesce(email,''))=$1 OR lower(coalesce(username,''))=$1 OR lower(coalesce(employee_id,''))=$1 OR ($2<>'' AND right(regexp_replace(coalesce(mobile,''),'\\D','','g'),10)=$2) LIMIT 1",[normalized,digits]); const user=rows[0]; if(!user||!user.active||!(await verifyPassword(password,user.password_hash))) throw new AppError(401,'Invalid username, employee ID, mobile/email, or password.'); return user; }
export async function changePassword(userId,currentPassword,newPassword){ const user=await findUserById(userId); if(!user||!(await verifyPassword(currentPassword,user.password_hash))) throw new AppError(400,'Current password is incorrect.'); await query('UPDATE users SET password_hash=$1,updated_at=$2 WHERE id=$3',[await hashPassword(newPassword),now(),userId]); }
export async function updateProfile(userId,values){ const allowed=['name','email','phone','area']; const fields=Object.entries(values).filter(([k,v])=>allowed.includes(k)&&v!==undefined); if(!fields.length) throw new AppError(400,'No profile fields supplied.'); const sets=[]; const params=[]; fields.forEach(([k,v],i)=>{sets.push(`${k}=$${i+1}`);params.push(v);}); params.push(now(),userId); try{await query(`UPDATE users SET ${sets.join(', ')},updated_at=$${params.length-1} WHERE id=$${params.length}`,params);}catch(e){if(e.code==='23505')throw new AppError(409,'That email is already in use.');throw e;} return findUserById(userId);}
export async function deactivateUser(userId,password){const user=await findUserById(userId); if(!user||!(await verifyPassword(password,user.password_hash))) throw new AppError(400,'Incorrect password. Please try again.'); await query('UPDATE users SET active=FALSE,updated_at=$1 WHERE id=$2',[now(),userId]);}
